# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bert_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bert_server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x62\x65rt_server.proto\"\x1a\n\x05Texts\x12\x11\n\tsentences\x18\x01 \x03(\t\"\x18\n\x04Text\x12\x10\n\x08sentence\x18\x01 \x01(\t\"#\n\x07Vectors\x12\x18\n\x07vectors\x18\x01 \x03(\x0b\x32\x07.Vector\"\x18\n\x06Vector\x12\x0e\n\x06vector\x18\x01 \x03(\x01\x32O\n\nBertServet\x12!\n\x0bget_vectors\x12\x06.Texts\x1a\x08.Vectors\"\x00\x12\x1e\n\nget_vector\x12\x05.Text\x1a\x07.Vector\"\x00\x62\x06proto3')
)




_TEXTS = _descriptor.Descriptor(
  name='Texts',
  full_name='Texts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentences', full_name='Texts.sentences', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=47,
)


_TEXT = _descriptor.Descriptor(
  name='Text',
  full_name='Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='Text.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=73,
)


_VECTORS = _descriptor.Descriptor(
  name='Vectors',
  full_name='Vectors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vectors', full_name='Vectors.vectors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=110,
)


_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector', full_name='Vector.vector', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=136,
)

_VECTORS.fields_by_name['vectors'].message_type = _VECTOR
DESCRIPTOR.message_types_by_name['Texts'] = _TEXTS
DESCRIPTOR.message_types_by_name['Text'] = _TEXT
DESCRIPTOR.message_types_by_name['Vectors'] = _VECTORS
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Texts = _reflection.GeneratedProtocolMessageType('Texts', (_message.Message,), {
  'DESCRIPTOR' : _TEXTS,
  '__module__' : 'bert_server_pb2'
  # @@protoc_insertion_point(class_scope:Texts)
  })
_sym_db.RegisterMessage(Texts)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'bert_server_pb2'
  # @@protoc_insertion_point(class_scope:Text)
  })
_sym_db.RegisterMessage(Text)

Vectors = _reflection.GeneratedProtocolMessageType('Vectors', (_message.Message,), {
  'DESCRIPTOR' : _VECTORS,
  '__module__' : 'bert_server_pb2'
  # @@protoc_insertion_point(class_scope:Vectors)
  })
_sym_db.RegisterMessage(Vectors)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR,
  '__module__' : 'bert_server_pb2'
  # @@protoc_insertion_point(class_scope:Vector)
  })
_sym_db.RegisterMessage(Vector)



_BERTSERVET = _descriptor.ServiceDescriptor(
  name='BertServet',
  full_name='BertServet',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=138,
  serialized_end=217,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_vectors',
    full_name='BertServet.get_vectors',
    index=0,
    containing_service=None,
    input_type=_TEXTS,
    output_type=_VECTORS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_vector',
    full_name='BertServet.get_vector',
    index=1,
    containing_service=None,
    input_type=_TEXT,
    output_type=_VECTOR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BERTSERVET)

DESCRIPTOR.services_by_name['BertServet'] = _BERTSERVET

# @@protoc_insertion_point(module_scope)
